#!/bin/bash

mkdir backend/runtime/logs;
mkdir frontend/runtime/logs;

touch backend/runtime/logs/access.log;
touch backend/runtime/logs/error.log;

touch frontend/runtime/logs/access.log;
touch frontend/runtime/logs/error.log;
